### ISSUE TITLE
All is OK except that i can not config the exporting options,like the svg export url

### ISSUE THREAD

**Issue by liyingquan** [NGI-Maghreb/ZK#1]
I have tried like this:
chart.setOptions("{url: 'http://www.abc.com/'}");
chart.setOptions("{exporting:{enabled: false}}");

And then,it still redirect to http://export.highcharts.com

**Comment by ziedzaiem** [comment]
In version 0.3.0 we added the setExporting method to set exporting options (http://api.highcharts.com/highcharts#exporting), use it like this:
chartComp.setExporting("{enableImages:true,
filename:'myChartname',
url:'http://www.abc.com',
width:2000}");

**Comment by ymissaoui** [comment]
still not working
