### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by FlameDuck** [NGI-Maghreb/ZK#2]
Hi.

I'm not quite sure what the license for this is. There is a GPL license in the zkdocs folder, but some of the source suggests LGPL.

I am considering using this for a commercial product, so an MIT-lik license would be best for me. I have also fixed a few issues to make it more compatible with modern versions of zk. I can delete these changes if they aren't compliant to the license.

**Comment by ziedzaiem** [comment]
ZHighCharts is released under a GPL license, but you need a valid Highcharts license to use it for commercial services, more details at https://github.com/NGI-Maghreb/ZK#licence

You're welcome to contribute to the project if you want, any help would be greatly appreciated by the ZK Community.
