### ISSUE TITLE
zhighcharts does not work with highcharts 3.0.2

### ISSUE THREAD

**Issue by FlameDuck** [NGI-Maghreb/ZK#3]
If you upgrade all the /lib files to highcharts 3.0.2 it will break. Hard. zk will be "processing" forever.

**Comment by ziedzaiem** [comment]
This is due to the HighCharts merge function causing a "too much recursion" error on Firefox / "Maximum call stack size exceeded." error on Chrome, we replaced it with the old one using jQuery.extend(true).
